FROM continuumio/miniconda3:23.5.2-0-alpine

RUN apk update && apk add git

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN cd /home && git clone https://github.com/martijnende/jDAS

EXPOSE 9000

CMD jupyter notebook --no-browser --port=9000 --ip='*' --allow-root --notebook-dir=/home
